$schema: https://json-schema.org/draft-07/schema
$defs:
  ApiSettings:
    properties:
      app_root_path:
        default: /api
        title: App Root Path
        type: string
      cors_allow_origin_regex:
        default: .*
        title: Cors Allow Origin Regex
        type: string
      db_url:
        examples:
        - postgresql+asyncpg://postgres:postgres@localhost:5432/postgres
        - postgresql+asyncpg://postgres:postgres@db:5432/postgres
        format: password
        title: Db Url
        type: string
        writeOnly: true
      files_dir:
        format: path
        title: Files Dir
        type: string
      secret_key:
        example: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        format: password
        title: Secret Key
        type: string
        writeOnly: true
      encryption_algorithm:
        default: HS256
        title: Encryption Algorithm
        type: string
      token_expiration_in_minutes:
        default: 60
        title: Token Expiration In Minutes
        type: integer
      unoserver_server:
        title: Unoserver Server
        type: string
      unoserver_port:
        title: Unoserver Port
        type: integer
    required:
    - db_url
    - secret_key
    - unoserver_server
    - unoserver_port
    title: ApiSettings
    type: object
  OpenAIRealtimeSettings:
    properties:
      model:
        title: Model
        type: string
      transcription_model:
        title: Transcription Model
        type: string
      language:
        title: Language
        type: string
      voice:
        default: verse
        title: Voice
        type: string
      base_sessions_url:
        default: https://api.openai.com/v1/realtime/client_secrets
        title: Base Sessions Url
        type: string
      token_expiration_in_seconds:
        default: 600
        title: Token Expiration In Seconds
        type: integer
    required:
    - model
    - transcription_model
    - language
    title: OpenAIRealtimeSettings
    type: object
  OpenAITextSettings:
    properties:
      api_key:
        format: password
        title: Api Key
        type: string
        writeOnly: true
      model:
        title: Model
        type: string
    required:
    - api_key
    - model
    title: OpenAITextSettings
    type: object
properties:
  api_settings:
    anyOf:
    - $ref: '#/$defs/ApiSettings'
    - type: 'null'
    default: null
  open_ai_text_settings:
    anyOf:
    - $ref: '#/$defs/OpenAITextSettings'
    - type: 'null'
    default: null
  open_ai_realtime_settings:
    anyOf:
    - $ref: '#/$defs/OpenAIRealtimeSettings'
    - type: 'null'
    default: null
title: Settings
type: object
