"""add table for interview messages

Revision ID: 45525e464b71
Revises: 116494dd7b2f
Create Date: 2025-09-08 23:45:24.421082

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "45525e464b71"
down_revision: Union[str, None] = "116494dd7b2f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "interview_message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["application_id"], ["application.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("interview_message")
    # ### end Alembic commands ###
