"""add weekly_hours_occupancy to vacancy model

Revision ID: d39afef08777
Revises: 5d2a30212b04
Create Date: 2025-08-31 22:19:17.810818

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d39afef08777"
down_revision: Union[str, None] = "5d2a30212b04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("vacancy", sa.Column("weekly_hours_occupancy", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vacancy", "weekly_hours_occupancy")
    # ### end Alembic commands ###
