"""add reason profile_url to application

Revision ID: 111111111111
Revises: 116494dd7b2f
Create Date: 2025-09-09 22:18:23.271913

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "111111111111"
down_revision: Union[str, None] = "116494dd7b2f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("application", sa.Column("profile_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("application", "profile_url")
    # ### end Alembic commands ###
