"""create emotional analysis and roadmap for post interview

Revision ID: 8b90595e4db2
Revises: 223f5407ccf3
Create Date: 2025-09-09 20:30:38.774575

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8b90595e4db2"
down_revision: Union[str, None] = "223f5407ccf3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("post_interview_result", sa.Column("emotional_analysis", sa.Text(), nullable=False))
    op.add_column("post_interview_result", sa.Column("candidate_roadmap", sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("post_interview_result", "candidate_roadmap")
    op.drop_column("post_interview_result", "emotional_analysis")
    # ### end Alembic commands ###
