"""add reason field for pre_interview_result

Revision ID: 116494dd7b2f
Revises: 0b23e5ea8874
Create Date: 2025-09-05 22:18:23.271913

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "116494dd7b2f"
down_revision: Union[str, None] = "0b23e5ea8874"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pre_interview_result", sa.Column("reason", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pre_interview_result", "reason")
    # ### end Alembic commands ###
