"""fix relations and types in models

Revision ID: 223f5407ccf3
Revises: dcd8eb5c079c
Create Date: 2025-09-09 19:01:31.444447

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "223f5407ccf3"
down_revision: Union[str, None] = "dcd8eb5c079c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "post_interview_result",
        "interview_summary",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.alter_column(
        "post_interview_result",
        "candidate_response",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.alter_column(
        "post_interview_result", "summary", existing_type=sa.VARCHAR(), type_=sa.Text(), existing_nullable=False
    )
    op.create_unique_constraint(None, "post_interview_result", ["application_id"])
    op.alter_column(
        "pre_interview_result", "reason", existing_type=sa.VARCHAR(), type_=sa.Text(), existing_nullable=True
    )
    op.create_unique_constraint(None, "pre_interview_result", ["application_id"])
    op.alter_column("vacancy", "description", existing_type=sa.VARCHAR(), type_=sa.Text(), existing_nullable=False)
    op.alter_column(
        "vacancy",
        "salary",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.DECIMAL(precision=10, scale=2),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "vacancy",
        "salary",
        existing_type=sa.DECIMAL(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column("vacancy", "description", existing_type=sa.Text(), type_=sa.VARCHAR(), existing_nullable=False)
    op.drop_constraint(None, "pre_interview_result", type_="unique")
    op.alter_column(
        "pre_interview_result", "reason", existing_type=sa.Text(), type_=sa.VARCHAR(), existing_nullable=True
    )
    op.drop_constraint(None, "post_interview_result", type_="unique")
    op.alter_column(
        "post_interview_result", "summary", existing_type=sa.Text(), type_=sa.VARCHAR(), existing_nullable=False
    )
    op.alter_column(
        "post_interview_result",
        "candidate_response",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "post_interview_result",
        "interview_summary",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
